### ISSUE TITLE
mvp checklist

### ISSUE THREAD

**Issue by michaelpalumbo** [michaelpalumbo/bcc4-timed-quiz#1]
- [x] GIVEN I am taking a code quiz
- [x] WHEN I click the start button
- [x] THEN a timer starts and I am presented with a question
- [x] WHEN I answer a question
- [x] THEN I am presented with another question
- [x] WHEN I answer a question incorrectly
- [x] THEN time is subtracted from the clock
- [x] WHEN all questions are answered or the timer reaches 0
- [x] THEN the game is over
- [x] WHEN the game is over
- [x] THEN I can save my initials and score

- [x] Application deployed at live URL.

- [x] Application loads with no errors.

- [x] Application GitHub URL submitted.

- [x] GitHub repository that contains application code.

- [x] Application user experience is intuitive and easy to navigate.
- [ ] 
- [x] Application user interface style is clean and polished.

- [x] Application resembles the mock-up functionality provided in the Challenge instructions.
- [x] Repository Quality: 13%
- [x] Repository has a unique name.

- [x] Repository follows best practices for file structure and naming conventions.

- [x] Repository follows best practices for class/id naming conventions, indentation, high-quality comments, etc.

- [x] Repository contains multiple descriptive commit messages.

- [x] Repository contains a high-quality README file with description, screenshot, and link to deployed application.

- [x] How to Submit the Challenge
- [x] You are required to submit BOTH of the following for review:

- [x] The URL of the functional, deployed application.

- [x] The URL of the GitHub repository. Give the repository a unique name and include a README describing the project.
